# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TmpRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmp', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
        ),
    ]
