# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperaturesApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TmpRecord',
            new_name='TmpReading',
        ),
    ]
