# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 17:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('temperaturesApp', '0002_auto_20160606_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpreading',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 6, 17, 12, 4, 74100, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
