# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('temperaturesApp', '0004_auto_20160606_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmpreading',
            name='timestamp',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
    ]
